name: C++ CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32 # For 32-bit compilation
        update: true
        install: >-
          mingw-w64-i686-toolchain

    - name: Compile DLL
      shell: msys2 {0} # Use msys2 shell and specify 32-bit mingw environment
      run: |
        echo "Compiling AllyMapperPoC.dll..."
        g++ -shared -m32 -o AllyMapperPoC.dll AllyMapperPoC.cpp -lxinput -luser32 -static-libgcc -static-libstdc++
        if [ $? -ne 0 ]; then
          echo "DLL Compilation failed!"
          exit 1
        fi
        echo "AllyMapperPoC.dll compiled successfully."

    - name: Compile Injector Executable
      shell: msys2 {0}
      run: |
        echo "Compiling WowAllyInjector.exe..."
        g++ -m32 -o WowAllyInjector.exe WowAllyInjector.cpp -static-libgcc -static-libstdc++ -std=c++17 -lstdc++fs
        if [ $? -ne 0 ]; then
          echo "Injector Compilation failed!"
          exit 1
        fi
        echo "WowAllyInjector.exe compiled successfully."

    - name: List files before artifact upload
      run: |
        echo "Files in current directory:"
        dir
      shell: cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WowAllyMapper-PoC-Build
        path: |
          AllyMapperPoC.dll
          WowAllyInjector.exe
          C:/msys64/mingw32/bin/libwinpthread-1.dll
          C:/msys64/mingw32/bin/libgcc_s_dw2-1.dll
          C:/msys64/mingw32/bin/libstdc++-6.dll 